### PR TITLE
Templated type

### PR DESCRIPTION
**Pull request by gsmecher**
Although this work is complete, it's intended as a discussion piece.

This patch series unites firpm_d and firpm_ld using templates, so the two types can operate from a single code base. The same approach should be possible for the firpm_mp tree, although there are some details (e.g. extra arguments) to work out there.

My goal, here, is to unify the code base so there is less duplication and inconsistency. It should be more manageable this way.

Although it's supposed to be equivalent to the old code base, not all of the tests pass. It's possible they already didn't. In any case, I have not taken a deep look at the behaviour of the algorithms: this is supposed to be purely mechanical.

### CODE REVIEW

**Comment by sfilip** [comment]
Neat! Thanks for the work. Yes, it should make it much more manageable. 

I was having some issues compiling the branch with clang, mainly because of the constexpr functions. Changed them to inline, which now compiles without issue with clang as well as gcc (on Linux and Mac OS targets). 

There were some lingering minor type inconsistencies that were causing some tests to fail. They should be fixed now. Both the d and ld versions of the tests now pass completely on the machines I have access to.

Continued with unification of the firpm_mp tree also. It's mostly done, but I'm still having some issues that were not manifesting before in certain tests. Simplified things by moving out the setup for the extra mpreal precision parameter prec. I was intending at some point to play around with changing the precision in the various functions, but have given up on that for the moment.

Also reworked the cmake scripts to only generate the firpm_mp functions if mpfr and gmp are found on the system.

**Comment by gsmecher** [comment]
I'm pleased you picked this PR and ran with it. I'm happy this is open-source code and it's a pleasure to contribute back.

I have a few other changes in mind, but they're logically distinct and I will organize them into separate merge requests. I have other tasks on the go, so it may take some time.

**Comment by sfilip** [comment]
I appreciate that you find it useful and the interest in improving the code.  Any ideas and changes you might have, I'm happy to discuss and integrate them. Whenever that may end up being.

I'm waiting to handle the remaining test issue in the mpreal version before I merge this. Hopefully will have it done soon.

**Comment by sfilip** [comment]
Ready to merge this PR. Some notable changes:

- templetized version of the library
- folder restructuring to reflect the unification
- optional requirement to build the mpfr version of the routines
- fixed some other small bugs found along the way + extra error check code

Thanks again @gsmecher for setting this up!

**Pull request merged**
